#version 460
layout(local_size_x=4, local_size_y=4, local_size_z=4) in;

layout(rgba32f, set = 0, binding = 0) uniform writeonly image3D volumeOut;
layout(set = 0, binding = 1) uniform sampler3D volumeIn;

layout(set = 0, binding = 2) uniform VolumeGenerationInputs
{
    uvec3 resolution;
} volumeGenerationInputs;

layout(set = 0, binding = 3) uniform DirShadower
{
    mat4 lightPV;
} shadower;
layout(set = 0, binding = 4) uniform sampler2D shadowMap;

void main() {

}
